import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/clerk-react";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

const Home: NextPage = () => {

  const user = useUser()

  //this code runs on user's device while the tRPC router code it calls runs on our servers
  const { data } = api.posts.getAll.useQuery();

  console.log(data)

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        {!user.isSignedIn && <SignInButton />}
        {!!user.isSignedIn && <SignOutButton />}
        <div>
          {data?.map((post) => (<div key={post.id} style={{color: 'white'}}>{post.content}</div>))}
        </div>
      </main>
    </>
  );
};

export default Home;
