import {
  SignIn,
  SignInButton,
  SignOutButton,
  useUser,
} from "@clerk/clerk-react";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { CreatePostWizard } from "./components/CreatePostWizard";
import { api } from "~/utils/api";
import { PostView } from "./components/PostView";
import router, { useRouter } from "next/router";

const Home: NextPage = () => {
  const user = useUser();
  console.log("soft reload");

  //this code runs on user's device while the tRPC router code it calls runs on our servers

  const router = useRouter();
  
  const { data, isLoading, error } = api.posts.getAll.useQuery();
  
  if (isLoading) return <div>Loading...</div>;
  if (!data) return <div>Something Went Wrong...</div>;

  console.log(data);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        {/* div is full width unless we are > threshold for md */}
        <div className="h-full w-full border-x border-slate-400 md:max-w-2xl">
          <div className="flex border-b-2 border-slate-400 p-4">
            {!user.isSignedIn && (
              <div className="flex justify-center">
                <SignInButton />
              </div>
            )}
            {!!user.isSignedIn && <CreatePostWizard />}
          </div>
          <div className="flex flex-col">
            {data?.map((fullPost) => (
              <PostView {...fullPost} key={fullPost.post.id} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
